language: csharp
solution: WF_lab_4.sln
install:
- nuget restore WF_lab_4/WF_lab_4.sln
- nuget install NUnit.Runners -Version 3.7.0 -OutputDirectory testrunner
script:
- xbuild /p:Configuration=Release WF_lab_4/WF_lab_4.sln
- mono ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./WF_lab_4/test/bin/Release/test.dll
