language: csharp
solution: calculator_tp_lab_1.sln
install:
- nuget restore calculator_tp_lab_1/calculator_tp_lab_1.sln
- nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
- xbuild /p:Configuration=Release calculator_tp_lab_1/calculator_tp_lab_1.sln
- nunit-console ./calculator_tp_lab_1/CalcTests/bin/Release/CalcTests.dll
