language: csharp
solution: WF_lab3.sln
 
install:
  - sudo apt-get install nunit-console
  - nuget restore ./WF_lab3/WF_lab3.sln
script:
  - xbuild WF_lab3.sln
  - nunit-console ./WF_lab3/test/bin/Release/test.dll
